routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'index');


Route::view('staticindex', 'index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {


    Route::get('/welcome', function () {
        return view('admin.welcome', ['route' => 'welcome']);
    })->name('admin.welcome');

    Route::resource('home', 'HomeController', ['only' => ['index', 'show', 'update', 'destroy']]);
    Route::resource('services', 'ServicesController', ['only' => ['index', 'update', 'show']]);
    Route::resource('blogs', 'BlogsController');
    Route::resource('portfolio', 'PortfolioController', ['only' => ['index', 'update', 'show']]);
    Route::resource('contact', 'ContactUsController', ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('contact-socialMedia', 'ContactUsController@showSocialMedia')->name('contact.showSocialMedia');
    Route::patch('contact-updatesocialmedia', 'ContactUsController@updatesocialmedia')->name('contact.updatesocialmedia');
    Route::delete('contact-deletesocialmedia/{id}', 'ContactUsController@deletesocialmedia')->name('contact.deletesocialmedia');
    Route::get('contact-inquiry', 'ContactUsController@inquieryIndex')->name('contact.inquiry');
});

Route::group(['namespace' => 'front'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::resource('contactus', 'ContactUsController', ['only' => ['index', 'store']]);
    Route::get('blog/{id}', 'HomeController@blogReadMore')->name('blog-readmore');
    Route::get('blogs', 'HomeController@blogViewAll')->name('blog-viewall');
    Route::get('privacy-policy', 'HomeController@privacypolicy');
    Route::get('terms-conditions', 'HomeController@termsconditions');
});

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::get('/changePassword', 'HomeController@showChangePasswordForm')->name('showChangePasswordForm');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
});

app/Models/Portfolio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
  protected $fillable = [
    'section_header',
    'section_title',
    'portfolio_item_andriod_url',
    'portfolio_item_ios_url',
    'portfolio_item_image',
    'portfolio_item_name',
    'portfolio_item_andriod',
    'portfolio_item_ios',
    'portfolio_item_name_color'
  ];
  protected $append = ['portfolio_item_image_big_url', 'portfolio_item_image_small_url'];

  public function setSectionHeaderAttribute($value)
  {
    $this->attributes['section_header'] = strtoupper($value);
  }
  public function setSectionTitleAttribute($value)
  {
    $this->attributes['section_title'] = ucfirst($value);
  }
  public function getPortfolioItemImageBigUrlAttribute()
  {
    return ($this->attributes['portfolio_item_image'] && file_exists('uploads/portfolio/big/' . $this->attributes['portfolio_item_image'])) ? asset('/uploads/portfolio/big/' . $this->attributes['portfolio_item_image']) : asset('/defaultimage/portfolio-big-defualt.jpg');
  }
  public function getPortfolioItemImageSmallUrlAttribute()
  {
    return ($this->attributes['portfolio_item_image'] && file_exists('uploads/portfolio/small/' . $this->attributes['portfolio_item_image'])) ? asset('/uploads/portfolio/small/' . $this->attributes['portfolio_item_image']) : asset('/defaultimage/portfolio-small-defualt.jpg');
  }
  public function getPortfolioItemIosUrlAttribute()
  {
      $str=$this->attributes['portfolio_item_ios_url'];
      if($str!=null){
        $substr=substr($str,0,4);
        if ($substr == 'http'){
            return $str;
        }else{
            return $this->attributes['portfolio_item_ios_url']='http://'.$str;
        }  
      }
  }
  public function getPortfolioItemAndriodUrlAttribute()
  {
    $str=$this->attributes['portfolio_item_andriod_url'];
    if($str!=null){
      $substr=substr($str,0,4);
      if ($substr == 'http'){
          return $str;
      }else{
          return $this->attributes['portfolio_item_andriod_url']='http://'.$str;
      }  
    }
 }
}

app/Http/Controllers/Admin/PortfolioController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\Admin\Request\PortfolioRequest;
use App\Models\Portfolio;
use Illuminate\Support\Arr;

class PortfolioController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        view()->share('route', 'portfolio');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $portfolios = Portfolio::all();
        return view('admin.portfolio.index', compact('portfolios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $id = $request->input('id');
        $portfolio = Portfolio::find($id);

        $output = [
            'section_header' => $portfolio->section_header,
            'section_title' => $portfolio->section_title,
            'portfolio_item_name' =>  $portfolio->portfolio_item_name,
            'android' => $portfolio->portfolio_item_andriod,
            'portfolio_item_andriod_url' => $portfolio->portfolio_item_andriod_url,
            'portfolio_item_ios_url' => $portfolio->portfolio_item_ios_url,
            'ios' => $portfolio->portfolio_item_ios,
            'portfolio_item_name_color'=>$portfolio->portfolio_item_name_color
        ];
        echo json_encode($output);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PortfolioRequest $request, $id)
    {

        $input = $request->persist();
        $portfolio = Portfolio::find($id);
        
        $image = $portfolio->portfolio_item_image;
        if (array_key_exists('portfolio_item_image', $input) && file_exists('uploads/portfolio/big/' . $image) && file_exists('uploads/portfolio/small/' . $image) && $image != "") {
            unlink('uploads/portfolio/big/' . $image);
            unlink('uploads/portfolio/small/' . $image);
        }

        if ($portfolio->fill($input)->save()) {
            return response()->json([
                'success' => true,
                'message' => 'User Added Successfully.',
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/portfolio/edit.blade.php
<div class="modal fade" id="portfolio_model">
  <div class="modal-dialog">
    <div class="modal-content">
      {{ html()->form()->id('portfolioForm')->acceptsFiles()->open() }} {{ csrf_field() }} @method('PATCH')
      <div class="modal-header">
        <h4 class="modal-title">Portfolio</h4>
        <button type="button" class="close closebtn" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-group section_header_model">
          {{ html() ->input('text', 'section_header') ->class('form-control section_header') ->id('section_header') ->placeholder('Enter Section Header') }}
          <div id="textlimit-header" class="textlimit">
            <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
          </div>
        </div>
        <div class="form-group section_title_model">
          {{ html() ->input('text', 'section_title') ->class('form-control section_title') ->id('section_title') ->placeholder('Enter Section Title') }}
          <div id="textlimit-title" class="textlimit">
            <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
          </div>
        </div>
        <div class="portfolio_item_model">
          <div class="form-group">
            {{ html()->file('portfolio_item_image') ->style(['border' => '1']) ->class('form-control portfolio_item_image') ->id('portfolio_item_image')
            ->attribute('value',asset('uploads/portfolio/'.$portfolio->portfolio_item_image)) }}
          </div>
          <div class="form-group">
            {{ html() ->input('text', 'portfolio_item_name') ->class('form-control portfolio_item_name') ->id('portfolio_item_name')
            ->placeholder('Enter Application Name ') }}
          </div>
          <div id="textlimit-itemname" class="textlimit">
            <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
          </div>
          <div class="form-group">
            {{ html() ->input('text', 'portfolio_item_name_color') ->class('form-control portfolio_item_name_color') ->id('portfolio_item_name_color')
            ->placeholder('Enter Color') }}
          </div>
         
          <div class="form-group">
            {{ html()->checkbox('android') ->class('android') }}
            <label style="display: inline-flex" for="is_unlimited_trials">Android</label> 
            {{ html() ->input('text', 'portfolio_item_andriod_url')
            ->class('form-control portfolio_item_andriod_url') ->id('portfolio_item_andriod_url') ->placeholder('Enter application Url For Android') }}
          </div>
          <div class="form-group">
            {{ html()->checkbox('ios') ->class('ios') }}
            <label style="display: inline-flex" for="is_unlimited_trials">iOS</label> {{ html() ->input('text', 'portfolio_item_ios_url')
            ->class('form-control portfolio_item_ios_url') ->id('portfolio_item_ios_url') ->placeholder('Enter application Url For iOS') }}
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <input type="hidden" name="hidden" id="portfolio_id">
        <button type="submit" class="btn btn-primary" id="portfolio_submit">Submit</button>
        <button type="button" class="btn btn-danger closebtn" data-dismiss="modal">Close</button>
      </div>
      <!-- </form> -->
      {{ html()->form()->close() }}
    </div>
  </div>
</div>

resources/views/admin/portfolio/index.blade.php
@extends('admin.layout.index')
@section('title') Portfolio
@stop
@section('page-css')
<link rel="stylesheet" href="/assets/css/main.css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.3/css/bootstrap-colorpicker.min.css" rel="stylesheet">


<style type="text/css">
.text-block h2 {
color: #5B79EE;
font-weight: 600;
margin-bottom: 5px;
}
</style>

@stop
@section('active-menu-icon')
<em class="fa fa-bar-chart">&nbsp;</em>
@stop
@section('active-menu') Portfolio
@stop
@section('page-header') Portfolio
@stop
@section('content')


<section id="portfolio" class="section-padding">
<!-- <div class="container"> -->
<div class="section-header text-center">
  <h5 class="wow fadeInDown">
    {{$portfolios[0]->section_header}}
    <a href="" id="1" data-toggle="modal" class="section_header_edit"> <i class='far fa-edit'></i></a>
  </h5>
  <h1 class="section-title wow fadeInDown" data-wow-delay="0.3s">
    {{$portfolios[0]->section_title}}
    <a href="" id="1" data-toggle="modal" class="section_title_edit"> <i class='far fa-edit'></i></a>
  </h1>
</div>
<div class="row">
  @php $count=$add=3;
  @endphp @foreach($portfolios as $key=>$portfolio) @if($key+1 == $count)
  <div class="col-xs-12 col-sm-12 col-lg-6 col-md-12">
    @php $portfolio_image=$portfolio->portfolio_item_image_big_url; $add=($add == 1)?5:1; $count += $add;
    @endphp @else
    <div class="col-xs-12 col-sm-12 col-lg-3 col-md-6">
      @php $portfolio_image=$portfolio->portfolio_item_image_small_url;
      @endphp @endif

      <a href="" id="{{$portfolio->id}}" data-toggle="modal" class="portfolio_item_edit" style="float: right;"> <i class='far fa-edit'></i></a>
      <div class="work-item wow fadeInLeft data-wow-delay="0.3s">
        <img src="{{$portfolio_image}}" class="image work-item-img">
        <div class="text-block">
          <h2 style="color:{{$portfolio->portfolio_item_name_color}}">{{$portfolio->portfolio_item_name}}</h2>
        </div>
        <div class="work-item-store">
          <div class="item-icon">
            @if($portfolio->portfolio_item_andriod)
            <a href="{!! url($portfolio->portfolio_item_andriod_url) !!}" target="_blank">
              <i class="hovicon effect-1 sub-a">
                <i class='fab fa-google-play'></i>
              </i>
            </a>             
            @endif @if($portfolio->portfolio_item_ios)
            <a href="{!! url($portfolio->portfolio_item_ios_url) !!}" target="_blank">
              <i class="hovicon effect-1 sub-a">
                <i class='fab fa-app-store-ios'></i>
              </i>
            </a> 
            @endif
          </div>
        </div>
      </div>
    </div>

    @endforeach
  </div>
</section>
@include('admin.portfolio.edit')
@stop

@section('page-js')

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.3/js/bootstrap-colorpicker.min.js"></script> 

<!-- color picker -->
<script>
   $('#portfolio_item_name_color').colorpicker({});
    $('.colorpicker').colorpicker({});
</script>

<!-- Open Particular fields to edit and summernote -->
<script>
  $(document).ready(function(){
    $(".section_header_edit").click(function(){
     $(".portfolio_item_model, .section_title_model").hide();
     $(".section_header_model").show();
   })
    $(".section_title_edit").click(function(){
     $(".portfolio_item_model, .section_header_model").hide();
     $(".section_title_model").show();
   });
    $(".portfolio_item_edit").click(function(){
      $(".section_header_model, .section_title_model").hide();
      $(".portfolio_item_model").show();
    });
    $('.android').click(function(){
     ($('.android').is(":checked"))?$(".portfolio_item_andriod_url").show():$(".portfolio_item_andriod_url").hide();
   });
    $('.ios').click(function(){
      ($('.ios').is(":checked"))?$(".portfolio_item_ios_url").show():$(".portfolio_item_ios_url").hide();
    })
  });

</script>

<!-- retrive data from database and show in model-->
<script>
  $(document).on('click', '.portfolio_item_edit,.section_header_edit,.section_title_edit', function(){
    var id = $(this).attr("id");
    $.ajax({
      url:"{{route('portfolio.show',$portfolio->id)}}",
      method:'get',
      data:{id:id},
      dataType:'json',
      success:function(data)
      {
        $('#section_header').val(data.section_header);
        $('#section_title').val(data.section_title);
        $('#portfolio_item_name').val(data.portfolio_item_name);
        $('#portfolio_item_andriod_url').val(data.portfolio_item_andriod_url);
        $('#android').prop('checked',data.android);
        $('#ios').prop('checked',data.ios);
        $('#portfolio_item_ios_url').val(data.portfolio_item_ios_url);
        $('#portfolio_item_name_color').val(data.portfolio_item_name_color);
        $('#portfolio_model').modal('show');
        $('#portfolio_id').val(id);
        
        ($('#android').is(":checked"))?$(".portfolio_item_andriod_url").show():$(".portfolio_item_andriod_url").hide();
        ($('#ios').is(":checked"))?$(".portfolio_item_ios_url").show():$(".portfolio_item_ios_url").hide();
        var textlable=document.getElementById("textlimit-header");
        textlimit('#section_header',30,textlable);
        var textlable=document.getElementById("textlimit-title");
        textlimit('#section_title',60,textlable);
        var textlable=document.getElementById("textlimit-itemname");
        textlimit('#portfolio_item_name',30,textlable);
      }
    })
  });
</script>

<!-- update data -->
<script>
  $(document).ready(function(){
   $('#portfolioForm').on('submit', function(event){
    var id = $('#portfolio_id').val();
    $('#portfolio_submit').attr("disabled", false);
    modelClose();
    $("#portfolio_submit").attr('disabled', 'disabled');
    event.preventDefault();
    $.ajax({
     url:'portfolio/'+id,
     method:"POST",
     data:new FormData(this),
     dataType:'JSON',
     contentType: false,
     cache: false,
     processData: false,
     success: function (data) {
     },
     error: function (response) {
     },
     complete: function(){
      $('#portfolio_submit').attr("disabled", false);
    }
  })
    .done(function(data) {
      window.location.reload(true);
    })
    .fail(function(data){
      $('#portfolio_submit').attr("disabled", false);
      var errors = data.responseJSON;
      if ($.isEmptyObject(errors) == false) {
        $.each(errors.errors, function (key, value) {
         $('#' + key)
         .closest('.form-group')
         .addClass('has-error')
         .append('<span class="help-block"><strong>' + value + '</strong></span>');
       });
      }
    });
  });
 });
</script>

<!-- check filesize textlimit and textarea lenght -->
<script type="text/javascript">
$(document).ready(function(){
  $("#portfolio_item_image").change(function(){
    filesize(this);
  });
  $("#section_header").keyup(function(){
    var textlable=document.getElementById("textlimit-header");
    textlimit(this,30,textlable);
  });
  $('#section_title').keyup(function(){
    var textlable=document.getElementById("textlimit-title");
    textlimit(this,60,textlable);
  });
  $('#portfolio_item_name').keyup(function(){
    var textlable=document.getElementById("textlimit-itemname");
    textlimit(this,30,textlable);
  });
  $(document).on('click', '.closebtn', function(){
    modelClose();
  });
});

</script>




@stop