routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'index');


Route::view('staticindex', 'index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {


    Route::get('/welcome', function () {
        return view('admin.welcome', ['route' => 'welcome']);
    })->name('admin.welcome');

    Route::resource('home', 'HomeController', ['only' => ['index', 'show', 'update', 'destroy']]);
    Route::resource('services', 'ServicesController', ['only' => ['index', 'update', 'show']]);
    Route::resource('blogs', 'BlogsController');
    Route::resource('portfolio', 'PortfolioController', ['only' => ['index', 'update', 'show']]);
    Route::resource('contact', 'ContactUsController', ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('contact-socialMedia', 'ContactUsController@showSocialMedia')->name('contact.showSocialMedia');
    Route::patch('contact-updatesocialmedia', 'ContactUsController@updatesocialmedia')->name('contact.updatesocialmedia');
    Route::delete('contact-deletesocialmedia/{id}', 'ContactUsController@deletesocialmedia')->name('contact.deletesocialmedia');
    Route::get('contact-inquiry', 'ContactUsController@inquieryIndex')->name('contact.inquiry');
});

Route::group(['namespace' => 'front'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::resource('contactus', 'ContactUsController', ['only' => ['index', 'store']]);
    Route::get('blog/{id}', 'HomeController@blogReadMore')->name('blog-readmore');
    Route::get('blogs', 'HomeController@blogViewAll')->name('blog-viewall');
    Route::get('privacy-policy', 'HomeController@privacypolicy');
    Route::get('terms-conditions', 'HomeController@termsconditions');
});

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::get('/changePassword', 'HomeController@showChangePasswordForm')->name('showChangePasswordForm');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
});

app/Models/Services.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Services extends Model
{
  protected $fillable = [
    'section_header',
    'section_title',
    'service_item_icon',
    'service_item_content_heading',
    'service_item_content_description'
  ];
  protected $append = ['service_item_icon_url', 'icon_bg_url'];

  public function setSectionHeaderAttribute($value)
  {
    $this->attributes['section_header'] = strtoupper($value);
  }
  public function setSectionTitleAttribute($value)
  {
    $this->attributes['section_title'] = ucfirst($value);
  }
  public function getServiceItemIconUrlAttribute()
  {
    return ($this->attributes['service_item_icon'] && file_exists('uploads/services/' . $this->attributes['service_item_icon'])) ? asset('/uploads/services/' . $this->attributes['service_item_icon']) : asset('/defaultimage/service-defualt.png');
  }
}

app/Http/Controllers/Admin/ServicesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\Admin\Request\ServicesRequest;
use App\Models\Services;
use Illuminate\Support\Arr;

class ServicesController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        view()->share('route', 'service');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Services::all();
        return view('admin.services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $id = $request->input('id');
        $services = Services::find($id);
        $output = [
            'section_header' => $services->section_header,
            'section_title' => $services->section_title,
            'service_item_content_heading'    =>  $services->service_item_content_heading,
            'service_item_content_description' => $services->service_item_content_description
        ];
        echo json_encode($output);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    { }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ServicesRequest $request, $id)
    {
        $input = $request->persist();
        $service = Services::find($id);
        $image = $service->service_item_icon;
        if (array_key_exists('service_item_icon', $input) && file_exists('uploads/services/' . $image) && $image != "") {
            unlink('uploads/services/' . $image);
        }
        if ($service->fill($input)->save()) {
            return response()->json([
                'success' => true,
                'message' => 'User Added Successfully.',
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/services/edit.blade.php
<div class="modal fade" id="services_model">
  <div class="modal-dialog">
    <div class="modal-content">

      {{ html()->form()->id('servicesForm')->acceptsFiles()->open() }} {{ csrf_field() }} @method('PATCH')
      <div class="modal-header">
        <h4 class="modal-title">Service</h4>
        <button type="button" class="close closebtn" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <!-- <div id="has-error"></div> -->
        <div class="form-group section_header_model">
          {{ html() ->input('text', 'section_header') ->class('form-control section_header') ->id('section_header') ->placeholder('Enter Section Header') }}
          <div id="textlimit-header" class="textlimit">
            <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
          </div>
        </div>
        <div class="form-group section_title_model">
          {{ html()->input('text', 'section_title')->class('form-control section_title')->id('section_title') ->placeholder('Enter Section Title') }}
          <div id="textlimit-title" class="textlimit">
            <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
          </div>
        </div>
        <div class="service_item_model">
          <div class="form-group">
            {{ html()->file('service_item_icon') ->style(['border' => '1']) ->class('form-control service_item_icon') ->id('service_item_icon')
            ->attribute('value',asset('uploads/services/'.$service->service_item_icon)) }}
          </div>
          <div class="form-group">
            {{ html() ->input('text', 'service_item_content_heading', old('service_item_content_heading', $service->service_item_content_heading))
            ->class('form-control service_item_content_heading') ->id('service_item_content_heading') ->placeholder('Enter item heading') }}
            <div id="textlimit-itemheading" class="textlimit">
              <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
            </div>
          </div>
          <div class="form-group">
            {{ html() ->textarea('service_item_content_description', old('service_item_content_description', $service->service_item_content_description))
            ->class('form-control service_item_content_description') ->id('service_item_content_description') ->placeholder('Enter item description') }}
            <div id="textlimit-itemdescription" class="textlimit">
              <label name="cur_text" id="cur_text"></label>/<label name="max_text" id="max_text"></label>
            </div>
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <input type="hidden" name="hidden" id="service_id">
        <button type="submit" class="btn btn-primary" id="service_submit" class="service_submit_btn">Submit</button>
        <button type="button" class="btn btn-danger closebtn" data-dismiss="modal">Close</button>
      </div>
      <!-- </form> -->
      {{ html()->form()->close() }}
    </div>
  </div>
</div>

resources/views/admin/services/index.blade.php
@extends('admin.layout.index')
@section('title') Services
@stop
@section('page-css')
<link rel="stylesheet" href="/assets/css/main.css">
@stop
@section('active-menu-icon')
<em class="fa fa-calendar"></em>

@stop
@section('active-menu') Services
@stop
@section('page-header') Services
@stop
@section('content')
<section id="services" class="section-padding">
  <div class="section-header text-center">
    <h5 class="wow fadeInDown">
      {{$services[0]->section_header}}
      <a href="" id="1" data-toggle="modal" class="section_header_edit"> <i class='far fa-edit'></i></a>
    </h5>
    <h1 class="section-title wow fadeInDown" data-wow-delay="0.3s">
      {{$services[0]->section_title}}
      <a href="" id="1" data-toggle="modal" class="section_title_edit"> <i class='far fa-edit'></i></a>
    </h1>
  </div>

  <div class="row">
    @foreach($services as $key => $service)
    <div class="col-md-6 col-lg-4 col-xs-12">
      <div class="services-item wow fadeInRight service-item-{{$service->id}}" data-wow-delay="0.3s">
        <a href="" id="{{$service->id}}" data-toggle="modal" class="services_item_edit" style="float: right;"> <i class='far fa-edit' ></i></a>
        <div class="services-item-icon">
          <i class="">
           <div class="service-item-img">
            @include('Icons.'.$service->id)
            <img id="" class="" height="50px" width="50px" src={{$service->service_item_icon_url}} />
          </div>
        </i>
      </div>
      <div class="services-content">
        <h3><a>{{$service->service_item_content_heading}}</a>
        </h3>
        <div>
          <p>{{$service->service_item_content_description}}</p>
        </div>
      </div>
    </div>
  </div>
  @include('admin.services.edit') @endforeach
</div>
</section>


@stop
@section('page-js')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<!-- Open Particular fields to edit and summernote -->
<script>
  $(document).ready(function(){
    $(".section_header_edit").click(function(){
     $(".service_item_model, .section_title_model").hide();
     $(".section_header_model").show();
   });

    $(".section_title_edit").click(function(){
     $(".service_item_model, .section_header_model").hide();
     $(".section_title_model").show();
   });

    $(".services_item_edit").click(function(){
      $(".section_header_model, .section_title_model").hide();
      $(".service_item_model").show();
    });
  });

</script>

<!-- retrive data from database and show in model-->
<script>
  $(document).on('click', '.services_item_edit,.section_header_edit,.section_title_edit', function(){
    var id = $(this).attr("id");
    $.ajax({
      url:"{{route('services.show',$service->id)}}",
      method:'get',
      data:{id:id},
      dataType:'json',
      success:function(data)
      {
        $('#section_header').val(data.section_header);
        $('#section_title').val(data.section_title);
        $('#service_item_content_heading').val(data.service_item_content_heading);
        $('#service_item_content_description').val(data.service_item_content_description);
        $('#services_model').modal('show');
        $('#service_id').val(id);
        var textlable=document.getElementById("textlimit-header");
        textlimit('#section_header',30,textlable);
        var textlable=document.getElementById("textlimit-title");
        textlimit('#section_title',60,textlable);
        var textlable=document.getElementById("textlimit-itemheading");
        textlimit('#service_item_content_heading',30,textlable);
        var textlable=document.getElementById("textlimit-itemdescription");
        textlimit('#service_item_content_description',130,textlable);
        service_item_content_description=document.getElementById("service_item_content_description");
        textarearow(service_item_content_description);
      }
    })
  });
</script>

<!-- update data -->
<script>
  $(document).ready(function(){
   $('#servicesForm').on('submit', function(event){
    var id = $('#service_id').val();
    $("#service_submit").attr('disabled', 'disabled');
    modelClose();
    event.preventDefault();
    $.ajax({
     url:'services/'+id,
     method:"POST",
     data:new FormData(this),
     dataType:'JSON',
     contentType: false,
     cache: false,
     processData: false,
     success: function (data) {
     },
     error: function (response) {
     },
     complete: function(){
      $('#service_submit').attr("disabled", false);
    }
  })
    .done(function(data) {
     window.location.reload(true);
   })
    .fail(function(data){
      $('#service_submit').attr("disabled", false);
      var errors = data.responseJSON;
      if ($.isEmptyObject(errors) == false) {
        $.each(errors.errors, function (key, value) {
         $('#' + key)
         .closest('.form-group')
         .addClass('has-error')
         .append('<span class="help-block"><strong>' + value + '</strong></span>');
       });
      }
    });
  });
 });
</script>

<!-- check filesize textlimit and textarea lenght -->
<script type="text/javascript">
  $(document).ready(function(){
    $("#service_item_icon").change(function(){
      filesize(this);
    });
    $("#section_header").keyup(function(){
      var textlable=document.getElementById("textlimit-header");
      textlimit(this,30,textlable);
    });
    $('#section_title').keyup(function(){
      var textlable=document.getElementById("textlimit-title");
      textlimit(this,60,textlable);
    });
    $('#service_item_content_heading').keyup(function(){
      var textlable=document.getElementById("textlimit-itemheading");
      textlimit(this,30,textlable);
    });
    $('#service_item_content_description').keyup(function(){
      textarearow(this);
      var textlable=document.getElementById("textlimit-itemdescription");
      textlimit(this,130,textlable);
    });
    $(document).on('click', '.closebtn', function(){
      modelClose();
    });
  });
</script>

@stop