routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'index');


Route::view('staticindex', 'index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {


    Route::get('/welcome', function () {
        return view('admin.welcome', ['route' => 'welcome']);
    })->name('admin.welcome');

    Route::resource('home', 'HomeController', ['only' => ['index', 'show', 'update', 'destroy']]);
    Route::resource('services', 'ServicesController', ['only' => ['index', 'update', 'show']]);
    Route::resource('blogs', 'BlogsController');
    Route::resource('portfolio', 'PortfolioController', ['only' => ['index', 'update', 'show']]);
    Route::resource('contact', 'ContactUsController', ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('contact-socialMedia', 'ContactUsController@showSocialMedia')->name('contact.showSocialMedia');
    Route::patch('contact-updatesocialmedia', 'ContactUsController@updatesocialmedia')->name('contact.updatesocialmedia');
    Route::delete('contact-deletesocialmedia/{id}', 'ContactUsController@deletesocialmedia')->name('contact.deletesocialmedia');
    Route::get('contact-inquiry', 'ContactUsController@inquieryIndex')->name('contact.inquiry');
});

Route::group(['namespace' => 'front'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::resource('contactus', 'ContactUsController', ['only' => ['index', 'store']]);
    Route::get('blog/{id}', 'HomeController@blogReadMore')->name('blog-readmore');
    Route::get('blogs', 'HomeController@blogViewAll')->name('blog-viewall');
    Route::get('privacy-policy', 'HomeController@privacypolicy');
    Route::get('terms-conditions', 'HomeController@termsconditions');
});

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::get('/changePassword', 'HomeController@showChangePasswordForm')->name('showChangePasswordForm');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
});

app/Models/ContactUs.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ContactUs extends Model
{
    protected $fillable = [
        'logo', 'footer_text', 'skype_id'
    ];

    protected $append = ['logo_url'];

    public function getLogoUrlAttribute()
    {
        return ($this->attributes['logo'] && file_exists('uploads/contactus/' . $this->attributes['logo'])) ? asset('/uploads/contactus/' . $this->attributes['logo']) : asset('/defaultimage/contactus-defualt.png');
    }
}

app/Http/Controllers/Admin/ContactUsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Domain\Admin\Datatables\InquiryDatatableScope;
use Illuminate\Http\Request;
use App\Domain\Admin\Request\ContactUsRequest;
use App\Domain\Admin\Request\SocialMediaRequest;
use App\Http\Controllers\Controller;
use App\Models\ContactUs;
use App\Models\Services;
use App\Models\SocialMediaIcon;
use Illuminate\Support\Arr;

class ContactUsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function inquieryIndex(InquiryDatatableScope $datatable)
    {
        view()->share('route', 'inquiry');

        if (request()->ajax()) {
            return $datatable->query();
        }

        return view('admin.contactus.inquiry', [
            'html' => $datatable->html(),
        ]);
    }

    public function index()
    {
        view()->share('route', 'contactus');
        $contact = ContactUs::first();
        $sociamedias = SocialMediaIcon::all();
        $services = Services::all();
        return view('admin.contactus.index', compact('contact', 'sociamedias', 'services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(ContactUsRequest $request)
    { }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $id = $request->input('id');
        $contact = ContactUs::find($id);
        $output = [
            'logo' => $contact->logo,
            'footer_text' => $contact->footer_text,
            'skype_id' => $contact->skype_id,
        ];
        echo json_encode($output);
    }

    public function showSocialMedia(Request $request)
    {
        $socialmedias['data'] = SocialMediaIcon::all();
        echo json_encode($socialmedias);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    { }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(ContactUsRequest $request, $id)
    {
        $input = $request->persist();
        $contactus = ContactUs::find($id);
        $image = $contactus->logo;
        if (array_key_exists('logo', $input) && file_exists('uploads/contactus/' . $image) && $image != '') {
            unlink('uploads/contactus/' . $image);
        }
        if ($contactus->fill($input)->save()) {
            return response()->json([
                'success' => true,
                'message' => 'User Added Successfully.',
            ]);
        }
    }

    public function updatesocialmedia(SocialMediaRequest $srequest)
    {
        foreach ($srequest->persist() as $value) {
            if ($value) {
                if ($value['id']) {
                    $socialmedia = SocialMediaIcon::find($value['id']);
                    $image = $socialmedia->icon;
                    if (array_key_exists('icon', $value) && file_exists(public_path('uploads/socialmedia/' . $image)) && $image != ' ') {
                        unlink(public_path('uploads/socialmedia/' . $image));
                    }
                }
                $input = Arr::except($value, ['id']);
                SocialMediaIcon::updateOrCreate(['id' => $value['id']], $input);
            }
        }
        return response()->json([
            'success' => true,
            'message' => 'User Added Successfully.',
        ]);
    }

    public function deletesocialmedia($id)
    {
        $socialmedia = SocialMediaIcon::find($id);
        ($socialmedia) ? $image = $socialmedia->icon : $image = ' ';
        if (file_exists(public_path('uploads/socialmedia/' . $image)) && $image != '') {
            unlink(public_path('uploads/socialmedia/' . $image));
        }
        SocialMediaIcon::whereId($id)->delete();

        return response()->json([
            'success' => 'Record deleted successfully!',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { }
}

app/Http/Controllers/front/ContactUsController.php
<?php

namespace App\Http\Controllers\front;

use Illuminate\Http\Request;
use App\Domain\Front\Request\InquiryRequest;
use App\Http\Controllers\Controller;
use App\Models\Inquiry;
use Mail;
use App\Mail\InquiryAdminMail;
use App\Mail\InquiryUserMail;
use Illuminate\Support\Arr;
use App\Jobs\SendEmailJob;

class ContactUsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(InquiryRequest $request)
    {
        $input=$request->persist();
        $input2 = Arr::except($input,['attachment_file']);
        if( Inquiry::create($input2)){
            Mail::to($request->email)->send(new InquiryUserMail($input));
            Mail::to(env('MAIL_USERNAME'))->send(new InquiryAdminMail($input));
             return response()->json([
                'success' => true,
                'message' => 'User Added Successfully.',
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/front/HomeController.php
<?php

namespace App\Http\Controllers\front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Blog;
use App\Models\ContactUs;
use App\Models\Home;
use App\Models\Portfolio;
use App\Models\Services;
use App\Models\SocialMediaIcon;
use Illuminate\Support\Arr;

class HomeController extends Controller
{
    public function index()
    {
        $blogs = Blog::all();
        $home = Home::first();
        $portfolios = Portfolio::all();
        $services = Services::all();
        $contact = ContactUs::first();
        $sociamedias = SocialMediaIcon::all();
        return view('front.index', compact('blogs', 'home', 'portfolios', 'services', 'contact', 'sociamedias'));
    }
    public function blogReadMore($id)
    {
        $blog = Blog::findorfail($id);
        $blogs = Blog::whereNotIn('id', [$id])->limit(3)->get();
        $contact = ContactUs::first();

        return view('front.blog.readmore', compact('contact', 'blog', 'blogs'));
    }
    public function blogViewAll()
    {
        $blogs = Blog::all();
        $contact = ContactUs::first();
        return view('front.blog.viewall', compact('blogs', 'contact'));
    }
    public function privacypolicy()
    {
        return view('front.privacypolicy.privacypolicy');
    }
    public function termsconditions()
    {
        return view('front.privacypolicy.termcondition');
    }
}

resources/views/front/contactus/index.blade.php
{{ html()->form()->id('contactusForm')->acceptsFiles()->open() }}
{{ csrf_field() }}
@method('POST')
<div class="row">
  <div class="col-lg-6">
    <div class="form-group">
      {{
        html()
        ->input('text', 'fullname')
        ->class('form-control fullname')
        ->id('fullname')
        ->placeholder('Enter Full Name *')

      }}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{
        html()
        ->input('email', 'email')
        ->class('form-control email')
        ->id('email')
        ->placeholder('Enter Email Address *')
      }}
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <div class="form-group">
      {{
        html()
        ->input('text', 'skype_id')
        ->class('form-control skype_id')
        ->id('skype_id')
        ->placeholder('Enter Skypeid *')
      }}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{
        html()
        ->input('text', 'country')
        ->class('form-control country')
        ->id('country')
        ->placeholder('Enter Country')
      }}
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <div class="form-group">
      {{
        html()
        ->input('text', 'project_type')
        ->class('form-control project_type')
        ->id('project_type')
        ->placeholder('Enter Project Type')
      }}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{
        html()
        ->input('text', 'budget')
        ->class('form-control budget')
        ->id('budget')
        ->placeholder('Enter your budget')
      }}
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="form-group">
      {{
        html()->file('attachment')
        ->style(['border' => '1','padding'=>'0'])
        ->class('form-control attachment')
        ->id('attachment')

      }}
    </div>

  </div>
  
</div>
<div class="row">
  <div class="col-lg-12">
   <div class="form-group">
    {{
      html()->textarea('description')
      ->style(['border' => '1'])
      ->class('form-control description')
      ->id('description')
      ->placeholder('Brief Project Description... *')
      ->attribute('rows', 7)
    }}
  </div>
</div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="success_msg" id="success_msg"></div>
  </div>
</div>
<div class="col-lg-12">
  <button type="submit" class="btn" id="submit"><i id="submit_load"></i> SEND QUERY</button>
</div> 
{{ html()->form()->close() }}  
<div id="has-error" style="width: 100%"></div> 

@section('page-js')
<script type="text/javascript">
 $(document).ready(function(){
   $('#contactusForm').on('submit', function(event){  
     $('form').find('.help-block').remove();
     $('form').find('.alert').removeClass('alert alert-danger');
     $('form').find('.form-group').removeClass('has-error');
     $('.alert-success').remove();
     $("#submit").attr('disabled', 'disabled');

     $("#submit_load").addClass('fa fa-spinner fa-spin');
     event.preventDefault();
     $.ajax({
       url:"{{route('contactus.store')}}",
       method:"POST",
       data:new FormData(this),
       dataType:'JSON',
       contentType: false,
       cache: false,
       processData: false,
       success: function (data) {    
       },
       error: function (response) {
       },
       complete: function(){
        $('#submit').attr("disabled", false);
        $("#submit_load").removeClass('fa fa-spinner fa-spin');
      }
    })
     .done(function(data) {
       $('.success_msg').append('<div class="alert alert-success" role="alert">Thank you! Your mail has been sent successfully.</div>');
       $("#contactusForm")[0].reset();
     })
     .fail(function(data){
      $('#submit').attr("disabled", false);
      $("#submit_load").removeClass('fa fa-spinner fa-spin');
      var errors = data.responseJSON;
      if ($.isEmptyObject(errors) == false) {
       $.each(errors.errors, function (key, value) {
        $('#' + key)
        .closest('.form-group')
        .addClass('has-error')
        .append('<span class="help-block"><strong>' + value + '</strong></span>');
      });
     }
   });
   });
 });
</script>
<script type="text/javascript">
  var uploadField = document.getElementById("attachment");
  uploadField.onchange = function() {
    $(this).closest('.row').removeClass('has-error');
    $(this).closest('.row').find('.help-block').remove();
    if(this.files[0].size > 2097152){
      console.log(uploadField)
      $(this).closest('.row')
      .addClass('has-error')
      .append('<span class="help-block" style="float:left;"><strong style="color:#a9444;">' + "* Image size must be less than 2 MB" + '</strong></span>');
      this.value = "";
    };
  };
</script>
@stop